### ISSUE TITLE
It’s unclear where to edit config file

### ISSUE THREAD

**Issue by KevinGutowski** [skpm/nib-loader#7]
> Add the following rule to your WebPack config:
>
> ```{
>  test: /\.(xib|nib)$/,
>  use: [
>    {
>      loader: '@skpm/nib-loader',
>      options: {}
>    }
>  ]
>}
>```

Do you mean the `package.json` file? Is this an option under `skpm`?

```
},
  "skpm": {
    "name": "Highlighter",
    "manifest": "src/manifest.json",
    "main": "highlighter.sketchplugin",
    "assets": [
      "assets/**/*"
    ],
    test: /\.(xib|nib)$/,
    use: [
    {
      loader: '@skpm/nib-loader',
      options: {}
    }
  ],
    "sketch-assets-file": "sketch-assets/icons.sketch"
  },
```

or somewhere else?

**Comment by KevinGutowski** [comment]
Oh I guess I already have some example code made from last year. Looks like I need to create a new `webpack.config.js` file and add this code:

```
module.exports = {
  test: /\.(xib|nib)$/,
  use: [
    {
      loader: '@skpm/nib-loader',
      options: {}
    }
  ]
}
```

**Comment by mathieudutour** [comment]
indeed, more precisely `webpack.skpm.config.js`: https://github.com/skpm/skpm/tree/master/template#webpack
